<a href="https://colab.research.google.com/github/LaraSantello/Introducao_Bioest_Python/blob/main/py03a_03_simulacao_introducao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Simulação Numérica - introdução

In [1]:
import os, sys, math # biblioteca do sistema operacional (os), biblioteca do sistema (sys), biblioteca de matemática (math)
import numpy as np # biblioteca numérica
import pandas as pd # biblioteca para trabalgo em tabelas
import seaborn as sns # biblioteca para gráficos e estatística
from scipy import stats # biblioteca especialmente para estatística do python
from statistics import mode # os valores esperados podem ser em média, mediana e moda
import matplotlib.pyplot as plt # matplotlib e seu alias plt
import matplotlib as mpl
# %matplotlib inline

In [2]:
mpl.__version__

'3.10.0'

### O que é frequência?
  - é a contagem de eventos

### Vamos jogar 1 vez o dado
  - Um dado tem 6 faces: 1 a 6
  - O Python sempre começa em zero (nas listas)
  - Logo, temos que forçar para que comece em 1 e termina em 7-1

### Vamos jogar várias vezes um dado: e analisar as frequências (1, 2....6)

### range

In [3]:
# iterator
r = range(6)
r

range(0, 6)

In [4]:
type(r)

range

In [5]:
list(r)

[0, 1, 2, 3, 4, 5]

In [6]:
# gerando uma lista de dados para entender
# isto não é um dado
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [7]:
# isto não é um dado
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [8]:
# isto não é um dado
np.arange(1,6)

array([1, 2, 3, 4, 5])

### Isto é um dado

In [9]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

## O que é array()
  - lista --> list() --> [] --> pode ter n elementos de qq tipo (int, float, string, boolean ..)
   - np.array() --> só aceita um tipo de variável e tem vários recursos diferentes do que a lista --> como uma lista

In [14]:
lista = [1,  1.5, 'ola']
lista

[1, 1.5, 'ola']

In [11]:
np.array(lista)

array(['1', '1.5', 'ola'], dtype='<U32')

In [15]:
arr = np.array([2, 5, 7, 8, 12]) # podem ser int ou float
arr

array([ 2,  5,  7,  8, 12])

In [16]:
arr.mean()

np.float64(6.8)

### Amostrando (sampling, np.random) 'jogar dados'
#### dê vários \<ctrl>+\<enter>

In [21]:
# simulação de jogar dados
dado = np.random.randint(1, 7)
dado

2

### Amostrando 'jogar dados' 5 vezes (loop ~ laço)

In [24]:
# np.random.seed(32)
for i in range(5):
    dado = np.random.randint(1, 7)
    print(dado)

3
6
1
6
2


### Qual a media esperada ao se jogar dados?

  - dado não viciado
  - todos os lados caem com a mesma change

In [25]:
# se todas as faces tem a mesma probabilidade de sair --> dado justo (fair die)
np.sum([1,2,3,4,5,6])/6

np.float64(3.5)

### Vamos jogar o dado 10 vezes

In [26]:
# criar uma sequencia de numeros de 1 a 6
np.arange(1, 7)

array([1, 2, 3, 4, 5, 6])

### Amostrar 10x um dado

In [27]:
%time

N=10

lista = []
for i in range(N):
    dado = np.random.randint(1, 7)
    lista.append(dado)

lista, len(lista), np.mean(lista), np.median(lista), np.std(lista)

CPU times: user 5 µs, sys: 0 ns, total: 5 µs
Wall time: 126 µs


([6, 4, 4, 6, 3, 3, 3, 1, 5, 2],
 10,
 np.float64(3.7),
 np.float64(3.5),
 np.float64(1.5524174696260025))

### Aumentar o N - desvio padrão tende ao desvio padrão 'populacional'

In [28]:
%time

N=10000

lista = []
for i in range(N):
    dado = np.random.randint(1, 7)
    lista.append(dado)

len(lista), np.mean(lista), np.median(lista), np.std(lista)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 5.96 µs


(10000, np.float64(3.4793), np.float64(3.0), np.float64(1.6981082150440237))

### Controlar tempos com %time

In [33]:
%time

N=20

lista = []
for i in range(N):
    dado = np.random.randint(1, 7)
    lista.append(dado)

f"media={np.mean(lista):.2f}  mediana={np.median(lista)}, desvio padrão amostral(SSD)={np.std(lista):.2f}"

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 4.77 µs


'media=3.95  mediana=5.0, desvio padrão amostral(SSD)=1.94'

### Aumentar o N do loop para analisar melhor os tempos

In [30]:
%time

N=100000

lista = []
# loop com np.arange
for i in np.arange(N):
    dado = np.random.randint(1, 7)
    lista.append(dado)

f"media={np.mean(lista):.2f} mediana={np.median(lista)}, desvio padrão amostral(SSD)={np.std(lista):.2f}"

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.77 µs


'media=3.50 mediana=3.0, desvio padrão amostral(SSD)=1.71'

In [32]:
%time

N=100000

lista = []
# loop com np.arange
for i in np.arange(N):
    dado = np.random.randint(1, 7)
    lista.append(dado)

mu = np.mean(lista)
med = np.median(lista)
SSD = np.std(lista)

print('')
f"media={mu:.2f} mediana={med}, desvio padrão amostral(SSD)={SSD:.2f}"

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 5.96 µs



'media=3.50 mediana=3.0, desvio padrão amostral(SSD)=1.71'

### Temos em %%time

  - user: usuário -> tempo utilizado para processar o comando na célula
  - sys: sistema -> tempo gasto para o sistema operacional fazer a chamada dos comandos
  - total: tempo do usuário + sistema
  - Wall time: tempo gasto desde o começo até o fim da operação (sistema operacional faz outras tarefas)


### Usando comprehension

In [ ]:
%time

# comprehension com loop
lista =  [np.random.randint(1, 7) for _ in range(N)]

mu = np.mean(lista)
med = np.median(lista)
SSD = np.std(lista)

print('')
f"media={mu:.2f} mediana={med}, desvio padrão amostral(SSD)={SSD:.2f}"

### Usando melhor randint

In [ ]:
%time

# usando direto a função randint (np.random)
lista =  np.random.randint(1, 7, size=N)

mu = np.mean(lista)
med = np.median(lista)
SSD = np.std(lista)

print('')
f"N={len(lista)} media={mu:.2f} mediana={med}, desvio padrão amostral(SSD)={SSD:.2f}"

### Jogar mais vezes --> aproximar do valor verdadeiro
#### Loop dentro de um Loop (laço)
  - Experimente N = 10, 100, 1000, 10000

In [ ]:
%time

for N in [10, 100, 1000, 10000]:

    lista =  np.random.randint(1, 7, size=N)
    stri = f"media={np.mean(lista):.1f}  mediana={np.median(lista):.1f}, desvio padrão amostral(SSD)={np.std(lista):.1f}"
    print(f'{N:5} -->', stri)


### Observações sutis:
  - Para N pequeno (N) a média pode até ser encontrada, mas o SSD é sempre subestimando - aqui no random qq resultado pode ocorrer
 - N pequeno, temos erro grande, N grande podemos ter o erro pequeno
  - GUARDEM ESTA INFORMAÇÃO

### Aumentando a precisão

In [31]:
%time

for N in [10, 100, 1000, 10000, 100000, 1000000]:

    lista =  np.random.randint(1, 7, size=N)
    stri = f"media={np.mean(lista):.3f}  mediana={np.median(lista):.3f}, desvio padrão amostral(SSD)={np.std(lista):.3f}"
    print(f'{N:7} -->', stri)


CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 8.11 µs
     10 --> media=3.900  mediana=4.000, desvio padrão amostral(SSD)=1.446
    100 --> media=3.300  mediana=3.000, desvio padrão amostral(SSD)=1.718
   1000 --> media=3.419  mediana=3.000, desvio padrão amostral(SSD)=1.703
  10000 --> media=3.508  mediana=4.000, desvio padrão amostral(SSD)=1.706
 100000 --> media=3.509  mediana=4.000, desvio padrão amostral(SSD)=1.705
1000000 --> media=3.499  mediana=3.000, desvio padrão amostral(SSD)=1.707


### Discutiremos MEDIANA nas próximas sessões

### O que acontece com a media e desvio padrão quando N é pequeno?

 - N pequeno, temos erro grande, N grande podemos ter o erro pequeno


### O que acontece com a media e desvio padrão quando N é grande?

 - N pequeno, temos erro grande, N grande podemos ter o erro pequeno


### População

  1. media é $\mu$ --> media populacional
  2. desvio padrão é $\sigma$ --> desvio padrão populacional

### Amostragem (experimental ou simulação)

  1. media é mu --> media amostral
  2. desvio padrão é SSD --> desvio padrão amostral (sample standard deviation)

### Perguntas

1. O que acontece com a media e o desvio padrão quando N é pequeno?
    * A media é qualquer valor (randômica, se N < 10) ou se aproxima da media populacional (com erros)
    * O SSD fica sempre subestimando  
2. O que acontece com a media e o desvio padrão quando N é muito grande?
    * A media tende à media populacional ($\mu$)
    * O SSD tende ao desvio padrão populacional ($\sigma$)

### Nós vamos estudar SEM - standard error of the mean - desvio padrão da média
