<a href="https://colab.research.google.com/github/LaraSantello/Introducao_Bioest_Python/blob/main/py03a_01_variaveis_randomicas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Variáveis Randômicas
  
Variáveis Randômicas são variáveis improváveis de predizer seus valores, denominamos:
  - **Variáveis Randômicas** ou **Variáveis Aleatórias**

**Simulação**: dado um modelo estatístico, uma variável aleatória pode ser obtida dada uma função matemática que retorna um valor numérico a cada resultado possível em um experimento aleatório ou dito randômico.

  - Vários experimentos repetidos permitem quantificar o valor esperado (média) e a incerteza (desvio padrão) experimental.
  - Várias simulações repetidas permitem quantificar o valor esperado (média) e a incerteza (desvio padrão) teórico computacional.

Uma variável randômica é representada por uma letra maiúscula (X) e pode ser discreta (valores enumeráveis, como o resultado de um dado) ou contínua (qualquer valor dentro de um intervalo, como a altura).

### Exemplos

  - Experimento de Bernoulli (jogar moedas)
    - Variável randômica: lado da moeda
    - Variável discreta e quantitativa: moeda tem 2 lados (cara=0, coroa=1) --> variavel nominal tranformada em inteiro
  - Binomial:
    - Jogar várias moedas simultaneamente  
      - 3 moedas: CCC, CCK ... KKK
    - Variável nominal --> transforma esta em discreta e quantitativa: contagem da combinação de resultados


### Dados experimentais ou simulados
  
  - **Quantitativos**
  - **Qualitativos**


| Tipo de dados | Descrição | Subtipos     |
| :---        |    :----:   |          ---: |
| Quantitativos      | são dados que consistem em números que representam contagens ou medidas  | Discretos ou Contínuos  |
| Qualitativos   | também chamados de categóricos ou "de atributos" podem ser separados/classificados em categorias que se distinguem por alguma característica não numérica        | Nominais, Ordinais, Intervalares, Razões  |

### Dados experimentais Quantitativos

| Tipo de dados | Origem | Exemplos     |
| :---        |    :----:   |          ---: |
| Discretos  |surgem quando o número de valores possíveis é ou um número finito ou uma quantidade enumerável | contagens: pessoas doentes, pessoas sãe, pessoas não infectadas, pessoas infectadas |
| Contínuos  | resultam de infinitos valores possíveis que correspondem a uma escala contínua que cobre um intervalo de valores sem vazios, interrupções ou saltos | medidas contínuas: temperatura, altura, peso  |

### Dados experimentais Qualitativos

| Tipo de dados | Origem | Exemplos     |
| :---        |    :----:   |          ---: |
| Nominais  |são dados que consistem em nomes, rótulos ou categorias | homem não é maior ou não vem primeiro que mulher |
| Ordinais  | podem ser arranjados em alguma ordem | programa da manhã, tarde, noite e madrugada |
| Intervalares  |é um dado ordinal onde a diferença é significativa – No entanto não tem ponto inicial (zero) - ou o zero é relativo (pode-se escolher) | faixas de temperaturas |
| Razões  | Dado ordinal, intervalar com origem (zero); onde zero significa origem e que a mensuração vale zero; As diferenças e razões são significante | faixas de peso, faixas de salário, faixas de preço |

## Como fazer simulações

### Variáveis discretas

In [1]:
import numpy as np

In [2]:
vars = np.arange(5)
vars

array([0, 1, 2, 3, 4])

### Variáveis discretas: incluso negativos

In [3]:
vars = np.arange(-5, 6)
vars

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

### Variáveis discretas: pulando números

In [4]:
vars = np.arange(-5, 6, step=2)
vars

array([-5, -3, -1,  1,  3,  5])

### Amostrando (sampling) variáveis discretas (sampling)
  - pacote numpy e no stats
  - pacote numpy --> random

In [7]:
# randint --> random de inteiros
# varios ctrl+enter
np.random.randint(100)

79

In [10]:
for i in range(5):
    print(np.random.randint(100))

54
60
59
81
85


#### Detalhe: não preciso usar 'i'

In [13]:
for _ in range(5):
    print(np.random.randint(100))

14
26
1
16
39


### Como eu faço para o Python repetir a randomização

In [16]:
# reprodução + randomicidade
np.random.seed(26)

for _ in range(5):
    print(np.random.randint(100))

53
62
6
48
65


### Guardando as variáveis

In [17]:
lista = []
for _ in range(5):
    var = np.random.randint(100)
    print(var)
    lista.append(var)

print("--------")
lista

83
77
90
32
68
--------


[83, 77, 90, 32, 68]

### Dados Experimentais Qualitativos

### Como transformar dados Qualitativos Ordinais/Nominais em Quantitativos

In [18]:
semanas = ['domingo', 'segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sábado'] # transformando as strings em números

In [19]:
list_sem = [1, 2, 3, 4, 5, 6, 7]

In [20]:
# Quantos dias?
len(semanas), len(list_sem)

(7, 7)

In [21]:
# media
np.mean(list_sem)

np.float64(4.0)

In [22]:
# mediana
np.median(list_sem)

np.float64(4.0)

In [23]:
# desvio padrão - SD
np.std(list_sem)

np.float64(2.0)

### Repita para o exemplo abaixo:

In [24]:
corrida = ['primeiro', 'segundo', 'terceiro', 'quarto-a-décimo', 'décimo primeiro-quinquagésimo']

In [25]:
mapeamento = {'primeiro':1, 'segundo':2, 'terceiro':3, 'quarto-a-décimo':4, 'décimo primeiro-quinquagésimo':5 }

In [26]:
corrida_quantitativa = [mapeamento[item] for item in corrida]

In [27]:
print(corrida_quantitativa)

[1, 2, 3, 4, 5]


In [ ]:
dor = ['sem dor', 'irritação', 'dor tolerável', 'dor muito forte', 'dor insumportável']

### Transforme dados qualitativos nominais em quantitativos: qual o significado

In [30]:
cores = ['amarelo', 'laranja', 'vermelho']

In [31]:
map_cores = {'amarelo':1, 'laranja':2, 'vermelho': 3}

In [32]:
trans_quantitivo = [map_cores[item] for item in cores]

In [33]:
print(trans_quantitivo)

[1, 2, 3]
